### ISSUE TITLE
T Box Mappings are mandatory

### ISSUE THREAD

**Issue by MBueschelberger** [MI-FraunhoferIWM/data2rdf#69]
In the A Box mode, the related data for each concept in the mapping is optional and data2rdf only throws a warning.

This does not seem to be the case in T Box mode:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Comment'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/data2rdf/parsers/utils.py", line 113, in _make_tbox_classes
    value = row[key]
            ~~~^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Comment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scripts/run.py", line 51, in <module>
    pipeline = Data2RDF(
               ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/data2rdf/pipelines/main.py", line 128, in run_pipeline
    self.parser = self.parser(
                  ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/data2rdf/parsers/base.py", line 262, in execute_parser
    self._tbox = self._tbox_parser(**arguments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/data2rdf/parsers/base.py", line 122, in run_parser
    cls._run_parser(self, datafile, mapping)
  File "/usr/local/lib/python3.12/site-packages/data2rdf/parsers/json.py", line 85, in _run_parser
    _make_tbox_classes(self, df, mapping)
  File "/usr/local/lib/python3.12/site-packages/data2rdf/parsers/utils.py", line 127, in _make_tbox_classes
    raise MappingMissmatchWarning(
data2rdf.warnings.MappingMissmatchWarning: Column with name `Comment` does not exist in provided worksheet.
```

**Comment by MBueschelberger** [comment]
This has been solved in #70
